// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Open Ingredient",
            "url": "https://github.com/open-ingredient"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/foods/chat/kcal": {
            "post": {
                "description": "Answers free-text questions about calories and nutrients using vector search + local LLM (Ollama).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foods"
                ],
                "summary": "RAG nutrition chat",
                "parameters": [
                    {
                        "description": "User question in Thai or English",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChatKcalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ChatKcalResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/foods/kcal": {
            "post": {
                "description": "Calculate total kcal from a list of ingredients with specified weights in grams. Nutrients are merged and summed across all items.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foods"
                ],
                "summary": "Calculate kilocalories",
                "parameters": [
                    {
                        "description": "Ingredient list with weights (weight_g \u003e 0)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CalcKcalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CalcKcalResponse"
                        },
                        "headers": {
                            "X-API-Version": {
                                "type": "string",
                                "description": "API version"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid body or weight_g ≤ 0",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "food_id not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/foods/search": {
            "get": {
                "description": "Search ingredients/foods by Thai or English name. Returns paginated results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foods"
                ],
                "summary": "Search foods",
                "parameters": [
                    {
                        "type": "string",
                        "example": "ข้าว",
                        "description": "Search keyword (Thai or English name)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SearchFoodResponse"
                        },
                        "headers": {
                            "X-API-Version": {
                                "type": "string",
                                "description": "API version"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/foods/semantic-search": {
            "post": {
                "description": "Embeds the query with OpenAI and returns the most similar foods using pgvector cosine distance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foods"
                ],
                "summary": "Semantic (vector) food search",
                "parameters": [
                    {
                        "description": "Search query and optional limit (1-100, default 10)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SemanticSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SemanticSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/foods/{id}": {
            "get": {
                "description": "Get a single food item with all its nutrients by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "foods"
                ],
                "summary": "Get food detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Food ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.FoodDetailResponse"
                        },
                        "headers": {
                            "X-API-Version": {
                                "type": "string",
                                "description": "API version"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Food not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CalcKcalRequest": {
            "type": "object",
            "properties": {
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.IngredientInput"
                    }
                }
            }
        },
        "handler.CalcKcalResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.KcalItemResponse"
                    }
                },
                "nutrients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.NutrientItem"
                    }
                },
                "total_kcal": {
                    "type": "number"
                }
            }
        },
        "handler.ChatKcalRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "ข้าวมันไก่ 1 จาน ให้กี่แคล"
                }
            }
        },
        "handler.ChatKcalResponse": {
            "type": "object",
            "properties": {
                "reply": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ChatKcalSource"
                    }
                }
            }
        },
        "handler.ChatKcalSource": {
            "type": "object",
            "properties": {
                "food_id": {
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "similarity": {
                    "type": "number"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.FoodDetailResponse": {
            "type": "object",
            "properties": {
                "energy_kcal": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "nutrients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.NutrientItem"
                    }
                },
                "source": {
                    "type": "string"
                },
                "weight_g": {
                    "type": "number"
                }
            }
        },
        "handler.FoodItem": {
            "type": "object",
            "properties": {
                "energy_kcal": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "weight_g": {
                    "type": "number"
                }
            }
        },
        "handler.IngredientInput": {
            "type": "object",
            "properties": {
                "food_id": {
                    "type": "integer"
                },
                "weight_g": {
                    "type": "number"
                }
            }
        },
        "handler.KcalItemResponse": {
            "type": "object",
            "properties": {
                "food_id": {
                    "type": "integer"
                },
                "kcal": {
                    "type": "number"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "weight_g": {
                    "type": "number"
                }
            }
        },
        "handler.NutrientItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "nutrient_id": {
                    "type": "integer"
                },
                "operator": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "handler.SearchFoodResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.FoodItem"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.SemanticSearchRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "handler.SemanticSearchResponse": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.SimilarFoodItem"
                    }
                }
            }
        },
        "handler.SimilarFoodItem": {
            "type": "object",
            "properties": {
                "food_id": {
                    "type": "integer"
                },
                "name_en": {
                    "type": "string"
                },
                "name_th": {
                    "type": "string"
                },
                "similarity": {
                    "type": "number"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Open Ingredient API",
	Description:      "REST API for searching food ingredients and calculating kilocalories.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
