FROM golang:1.25-alpine

RUN apk --no-cache add ca-certificates tzdata && \
    go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
